"""Order and Trade data classes, plus tick-snapping utility."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import ROUND_HALF_UP, Decimal


# ── Tick snapping ─────────────────────────────────────────────────────────────

def snap_to_tick(price: float, tick_size: float) -> float:
    """Round *price* to the nearest multiple of *tick_size*.

    Uses ``Decimal`` arithmetic (via string conversion) to avoid the
    floating-point representation errors that plague naive
    ``round(price / tick_size) * tick_size`` implementations.
    """
    if tick_size <= 0:
        return price
    d_price = Decimal(str(price))
    d_tick  = Decimal(str(tick_size))
    snapped = (d_price / d_tick).quantize(Decimal("1"), rounding=ROUND_HALF_UP) * d_tick
    return float(snapped)


# ── Order ─────────────────────────────────────────────────────────────────────

@dataclass
class Order:
    """A pending entry order placed by the user.

    Parameters
    ----------
    id:
        UUID string (auto-generated by factory methods).
    session_id:
        Session the order belongs to.
    side:
        ``'long'`` or ``'short'``.
    order_type:
        ``'market'``, ``'limit'``, or ``'stop'``.
    price:
        Limit / stop trigger price.  ``None`` for market orders.
    quantity:
        Number of units.
    stop_price:
        OCO bracket stop level (``None`` → no stop).
    target_price:
        OCO bracket target level (``None`` → no target).
    status:
        ``'pending'``, ``'filled'``, or ``'cancelled'``.
    created_at_index:
        Bar index at which the order was submitted.
    tick_size:
        Instrument tick size used for price snapping.
    """

    id:               str
    session_id:       str
    side:             str            # 'long' | 'short'
    order_type:       str            # 'market' | 'limit' | 'stop'
    price:            float | None   # None for market
    quantity:         float
    stop_price:       float | None
    target_price:     float | None
    status:           str            # 'pending' | 'filled' | 'cancelled'
    created_at_index: int
    tick_size:        float

    # ------------------------------------------------------------------
    # Factory helpers
    # ------------------------------------------------------------------

    @classmethod
    def market(
        cls,
        session_id:    str,
        side:          str,
        quantity:      float,
        tick_size:     float,
        created_at_index: int,
        stop_price:    float | None = None,
        target_price:  float | None = None,
    ) -> "Order":
        """Create a market entry order."""
        return cls(
            id               = str(uuid.uuid4()),
            session_id       = session_id,
            side             = side,
            order_type       = "market",
            price            = None,
            quantity         = quantity,
            stop_price       = snap_to_tick(stop_price,   tick_size) if stop_price   is not None else None,
            target_price     = snap_to_tick(target_price, tick_size) if target_price is not None else None,
            status           = "pending",
            created_at_index = created_at_index,
            tick_size        = tick_size,
        )

    @classmethod
    def limit(
        cls,
        session_id:       str,
        side:             str,
        quantity:         float,
        limit_price:      float,
        tick_size:        float,
        created_at_index: int,
        stop_price:       float | None = None,
        target_price:     float | None = None,
    ) -> "Order":
        """Create a limit entry order."""
        return cls(
            id               = str(uuid.uuid4()),
            session_id       = session_id,
            side             = side,
            order_type       = "limit",
            price            = snap_to_tick(limit_price, tick_size),
            quantity         = quantity,
            stop_price       = snap_to_tick(stop_price,   tick_size) if stop_price   is not None else None,
            target_price     = snap_to_tick(target_price, tick_size) if target_price is not None else None,
            status           = "pending",
            created_at_index = created_at_index,
            tick_size        = tick_size,
        )

    @classmethod
    def stop_entry(
        cls,
        session_id:       str,
        side:             str,
        quantity:         float,
        stop_price:       float,
        tick_size:        float,
        created_at_index: int,
        bracket_stop:     float | None = None,
        bracket_target:   float | None = None,
    ) -> "Order":
        """Create a stop-entry order (buy stop or sell stop)."""
        return cls(
            id               = str(uuid.uuid4()),
            session_id       = session_id,
            side             = side,
            order_type       = "stop",
            price            = snap_to_tick(stop_price, tick_size),
            quantity         = quantity,
            stop_price       = snap_to_tick(bracket_stop,   tick_size) if bracket_stop   is not None else None,
            target_price     = snap_to_tick(bracket_target, tick_size) if bracket_target is not None else None,
            status           = "pending",
            created_at_index = created_at_index,
            tick_size        = tick_size,
        )


# ── OpenPosition (internal FillEngine state) ──────────────────────────────────

@dataclass
class OpenPosition:
    """An entry that has filled, awaiting an exit (stop, target, or manual)."""

    order_id:          str
    session_id:        str
    side:              str            # 'long' | 'short'
    entry_price:       float
    entry_datetime:    str
    quantity:          float
    stop_price:        float | None
    target_price:      float | None
    tick_size:         float
    ambiguous:         bool  = field(default=False)
    slippage_pnl_cost: float = field(default=0.0)


# ── Trade (completed round-trip) ──────────────────────────────────────────────

@dataclass
class Trade:
    """A completed round-trip trade, ready to be persisted to the DB.

    Field names match the ``trades`` table schema in CLAUDE.md exactly.
    ``db_id`` is ``None`` until the row is written to SQLite.

    The three fields without defaults (``entry_price``, ``side``,
    ``quantity``) are listed first so that partial construction is
    valid in tests.  All existing call sites use keyword arguments and
    are unaffected by the reordering.
    """

    # Required — no defaults
    entry_price:      float
    side:             str            # 'long' | 'short'
    quantity:         float

    # Optional — sensible defaults allow partial construction in tests
    session_id:       str            = ""
    symbol:           str            = ""
    timeframe:        str            = ""
    entry_datetime:   str            = ""
    exit_datetime:    str            = ""
    exit_price:       float          = 0.0
    stop_price:       float | None   = None
    target_price:     float | None   = None
    exit_reason:      str            = ""   # 'stop'|'target'|'manual'|'timeout'
    pnl_currency:     float          = 0.0
    pnl_r:            float | None   = None  # None when no stop defined
    commission:       float          = 0.0
    slippage:         float          = 0.0
    tick_size:        float          = 0.01
    execution_rule:   str            = "default"  # 'default'|'conservative'|'optimistic'|'unknown'
    ambiguity_flag:   int            = 0     # 0 or 1
    notes:            str | None     = None
    config_hash:      str            = ""
    db_id:            int | None     = field(default=None, compare=False)
    status:           str            = "open"   # 'open' | 'closed'
